services:
  - type: web
    name: mindmate-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn mindmate_wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 30
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true 